Repository ay2306/graphviz-cp-simplifier, pull requests merged in 2022-10, with the labels that each got.

#15 Create requirements.txt
  requirements.txt
Labels: hacktoberfest-accepted

#18 Update Contributing.md
  Contributing.md
Labels: hacktoberfest, hacktoberfest-accepted

#17 Updated readme file
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#21 Renamed the variable vis to visualizer
  dsa_animator/animator_service/animations/cycle_detection_directed_graph.py
  dsa_animator/animator_service/animations/multisoure_bfs.py
Labels: hacktoberfest-accepted
